#!/bin/bash

T="/home/www/archives"

[ "$1" ] && T=$1

for i in `ls $T/imports/`; do  
    if [ ! -e "$T/images/$i.png" ]; then 
	/usr/bin/ogg123 \
	    -d wav \
	    -f - \
	    $T/imports/${i} \
	    | /usr/local/bin/wav2png \
		  --background-color=000000ff \
		  --db-max 3 \
		  --db-min -40 \
		  --foreground-color=ff00ffaa \
		  --height 65 \
		  --width 420 \
		  -d \
		  -o $T/images/${i}.png \
		  /dev/stdin; 
    fi
done
